spring.application.name=doacao-leite
spring.profiles.active=dev

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWTSECRET:mysecretkey}
jwt.expiration=${JWTEXPIRATION:168}

logging.level.org.springframework.web=DEBUG
server.tomcat.max-http-header-size=16384
